name: circlehunter
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aioeasywebdav=2.4.0
  - aiohttp=3.6.2
  - amply=0.1.4
  - appdirs=1.4.3
  - async-timeout=3.0.1
  - atk=2.36.0
  - atk-1.0=2.36.0
  - attmap=0.13.0
  - attrs=20.2.0
  - autopep8=1.5.5
  - bcrypt=3.2.0
  - bedtools=2.29.2
  - blas=1.0
  - boto3=1.15.1
  - botocore=1.18.1
  - bowtie2=2.4.2
  - brotlipy=0.7.0
  - bwa=0.7.17
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2021.1.19
  - cachetools=4.1.1
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.3
  - chardet=3.0.4
  - coincbc=2.10.5
  - configargparse=1.2.3
  - cryptography=3.1
  - datrie=0.8.2
  - decorator=4.4.2
  - docutils=0.16
  - dropbox=10.4.1
  - expat=2.2.9
  - fastp=0.20.1
  - fftw=3.3.8
  - filechunkio=1.8
  - filelock=3.0.12
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.2
  - fribidi=1.0.10
  - ftputil=4.0.0
  - gdk-pixbuf=2.38.2
  - gettext=0.19.8.1
  - ghostscript=9.53.3
  - giflib=5.2.1
  - gitdb=4.0.5
  - gitpython=3.1.8
  - glib=2.66.0
  - gobject-introspection=1.66.1
  - google-api-core=1.22.2
  - google-api-python-client=1.12.5
  - google-auth=1.21.2
  - google-auth-httplib2=0.0.4
  - google-cloud-core=1.4.1
  - google-cloud-storage=1.31.0
  - google-crc32c=1.0.0
  - google-resumable-media=1.0.0
  - googleapis-common-protos=1.51.0
  - graphite2=1.3.13
  - graphviz=2.42.3
  - grpcio=1.31.0
  - gtk2=2.24.32
  - gts=0.7.6
  - harfbuzz=2.7.2
  - htslib=1.10.2
  - httplib2=0.18.1
  - icu=67.1
  - idna=2.10
  - idna_ssl=1.1.0
  - imagemagick=7.0.10_28
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - iniconfig=1.1.1
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jinja2=2.11.2
  - jmespath=0.10.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_core=4.6.3
  - krb5=1.17.1
  - ld_impl_linux-64=2.35
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcrc32c=1.1.1
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libprotobuf=3.13.0
  - librsvg=2.50.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.1.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - logmuse=0.2.6
  - lz4-c=1.9.2
  - macs2=2.2.7.1
  - markupsafe=1.1.1
  - more-itertools=8.7.0
  - multidict=4.7.5
  - nbformat=5.0.8
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauth2client=4.1.3
  - openjpeg=2.3.1
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.1.2
  - pango=1.42.4
  - paramiko=2.7.2
  - pcre=8.44
  - peppy=0.31.0
  - perl=5.26.2
  - pip=20.2.3
  - pixman=0.38.0
  - pkg-config=0.29.2
  - pluggy=0.13.1
  - prettytable=0.7.2
  - protobuf=3.13.0
  - psutil=5.7.2
  - pthread-stubs=0.4
  - pulp=2.3.1
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pygments=2.7.2
  - pygraphviz=1.6
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysam=0.16.0.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.6.11
  - python-dateutil=2.8.1
  - python-irodsclient=0.8.2
  - python_abi=3.6
  - pytz=2020.1
  - pyyaml=5.3.1
  - r-base=3.2.2
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.24.0
  - rsa=4.6
  - s3transfer=0.3.3
  - samblaster=0.1.26
  - samtools=1.10
  - scipy=1.4.1
  - setuptools=49.6.0
  - simplejson=3.17.2
  - six=1.15.0
  - slacker=0.14.0
  - smart_open=5.0.0
  - smmap=3.0.4
  - snakemake=6.1.0
  - snakemake-minimal=6.1.0
  - sqlite=3.33.0
  - tbb=2020.2
  - tk=8.6.10
  - toml=0.10.1
  - toposort=1.5
  - traitlets=4.3.3
  - typing_extensions=3.7.4.2
  - ubiquerg=0.6.1
  - uritemplate=3.0.1
  - urllib3=1.25.10
  - veracitools=0.1.3
  - wheel=0.35.1
  - wrapt=1.12.1
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.4.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
