name: circlehunter
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake=7.17.1
  - fastp=0.20.1
  - bwa=0.7.17
  - samblaster=0.1.26
  - samtools=1.10
  - bedtools=2.29.2
  - macs2=2.2.7.1
  - networkx=2.5
  - pandas=1.1.2
  - pysam=0.16.0.1
  - scipy=1.9.1
  - pybedtools=0.9.0
  - pyfaidx=0.7.1
  - art=2016.06.05
